apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: milky-way
resources:
  - namespace.yaml
  - frontend-deployment.yaml
  - api-gateway-deployment.yaml
  - agent-engine-deployment.yaml
  - worker-pool-deployment.yaml
  - metadata-db-statefulset.yaml
  - cache-statefulset.yaml
  - vector-store-statefulset.yaml
  - hpa.yaml
